apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-microservice-chart.fullname" . }}-config
  labels:
    {{- include "go-microservice-chart.labels" . | nindent 4 }}
data:
  APP_ENV: "{{ .Values.app.env  }}"
  APP_PORT: "{{ .Values.app.port }}"
  LOG_LEVEL: "{{ .Values.app.logLevel }}"
