apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go-demo-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore      # <--- important
    name: aws-secret-store
  target:
    name: go-demo-go-microservice-chart-secret
    creationPolicy: Owner
  data:
    - secretKey: PLACEHOLDER_SECRET
      remoteRef:
        key: week1/go-microservice/placeholder
        property: PLACEHOLDER_SECRET
